### ISSUE TITLE
graven stp j'ai un pb avec ton programme

### ISSUE THREAD

**Issue by aniito** [GravenilvecTV/ASCIIArt#2]
ça me met : python not found

**Comment by azgar44** [comment]
t'es con

**Comment by azgar44** [comment]
il faut utiliser le path windows

**Comment by aniito** [comment]
non je suis pas sionniste

**Comment by azgar44** [comment]
graven je t'aime

**Comment by aniito** [comment]
> les nazi ont servit Aryens

il a raison ce con

**Comment by ghost** [comment]
Poutine le script kiddy en sueur mdrr

**Comment by aniito** [comment]
Kremlin le nouveau yahourt de nos regions

**Comment by ghost** [comment]
close ton issue frère
